# Generated by Django 3.1.3 on 2020-11-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('s', 'stallion'), ('m', 'mare'), ('g', 'gelding')], max_length=1)),
                ('breed', models.CharField(choices=[('sb', 'Standardbred'), ('ft', 'French trotter'), ('rt', 'Russian trotter'), ('fh', 'Finn horse'), ('nsh', 'North Swedish horse'), ('sp', 'Shetland pony'), ('gp', 'Gotland pony')], max_length=3)),
                ('color', models.CharField(choices=[('c', 'chestnut'), ('ba', 'bay'), ('bl', 'black'), ('g', 'gray'), ('p', 'pinto')], max_length=2)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
